#! /bin/sh

case "$1" in
    start)
        echo "Starting scull devices"
        /etc/init.d/scull_load.sh
        ;;
    stop)
        echo "Stopping scull devices"
        /etc/init.d/scull_unload.sh
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
exit 0
